# Generated by Django 6.0.4 on 2026-04-29 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(max_length=255)),
                ('estimated_time_per_item', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='date',
        ),
        migrations.AddField(
            model_name='timeentry',
            name='amount_of_elements',
            field=models.PositiveIntegerField(default=1, verbose_name='Number of elements produced'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Exit Time'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='start_time',
            field=models.DateTimeField(verbose_name='Entry Time'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='data.element'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='machine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='data.machine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='id_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='data.machinetype'),
        ),
        migrations.AddField(
            model_name='element',
            name='id_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='data.machinetype'),
        ),
        migrations.CreateModel(
            name='UserMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to='data.machine')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_machines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
